version: '3.7'

services:

 init:
  container_name: init
  # image: mpgagebioinformatics/myapp:stable
  build:
    context: ./
    dockerfile: Dockerfile
    args:
      MYAPP_VERSION: dev
  user: root
  entrypoint: /myapp/services/init/entrypoint.sh
  volumes:
    - data:/myapp_data/users
    - ~/flaski3_backup/stats:/backup/stats
    - ~/flaski3_backup/users_data:/backup/users_data
    - ~/flaski3_backup/mariadb:/backup/mariadb:ro
  environment:
    - APP_NAME=myapp
    - APP_URL=https://0.0.0.0
    - FLASK_ENV=init
    - DB_NAME=myapp
    - RESTORE_DB=1
    - RESTORE_USERS_DATA=1
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - SECRET_KEY=${SECRET_KEY}
    - REDIS_ADDRESS=redis:6379/0
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - MYSQL_USER=myapp
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_HOST=mariadb
    - MYSQL_PORT=3306
    - ADMINS=jboucas@gmail.com
  links:
    - mariadb
  depends_on:
    - mariadb

 server:
  container_name: server
  # image: mpgagebioinformatics/myapp:stable
  build:
    context: ./
    dockerfile: Dockerfile
    args:
      APP_VERSION: dev
  restart: always
  volumes:
   - data:/myapp_data/users/
   - ./static/dog-solid.png:/myapp/myapp/static/favicon.ico
   - ./static/dog-solid.png:/myapp/myapp/static/logo.png
   - ./pyflaski/pyflaski:/myapp/pyflaski
   - ./routes/apps:/myapp/myapp/routes/apps
  #  - ~/myapp/myapp/routes/login.py:/myapp/myapp/routes/login.py
  #  - ~/myapp/myapp/routes/register.py:/myapp/myapp/routes/register.py
  #  - ~/myapp/myapp/models.py:/myapp/myapp/models.py
   - ./routes/_routes.py:/myapp/myapp/routes/_routes.py
   - ./routes/home.py:/myapp/myapp/routes/home.py
   - ./routes/_impressum.py:/myapp/myapp/routes/_impressum.py
   - ./routes/_vars.py:/myapp/myapp/routes/_vars.py
   - ./routes/_privacy.py:/myapp/myapp/routes/_privacy.py
   - ./routes/_about.py:/myapp/myapp/routes/_about.py
   - ./email/app_exception.html:/myapp/myapp/templates/email/app_exception.html
   - ./email/app_exception.txt:/myapp/myapp/templates/email/app_exception.txt
   - ./email/app_help.html:/myapp/myapp/templates/email/app_help.html
   - ./email/app_help.txt:/myapp/myapp/templates/email/app_help.txt
   - ~/flaski3_private:/myapp_private:ro
  environment:
   - APP_NAME=myapp
   - APP_TITLE=flaski
   - APP_URL=https://0.0.0.0 # eg. https://0.0.0.0/v3 for a /v3 PAGE_PREFIX
  #  - PAGE_PREFIX=/v3 # eg . /v3   - LOGS=/var/log/myapp/
   - SECRET_KEY=${SECRET_KEY}
   - REDIS_ADDRESS=redis:6379/0
   - REDIS_PASSWORD=${REDIS_PASSWORD}
   - DB_NAME=myapp
   - MYSQL_USER=myapp
   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   - MYSQL_HOST=mariadb
   - MYSQL_PORT=3306
   - FLASK_ENV=development
   - PRIVATE_APPS=/myapp_private/private.apps.tsv
   - INSTANCE=(DEV)
   - ADMINS=jboucas@gmail.com
   - MAIL_USERNAME=jboucas@gmail.com
  links:
   - mariadb
   - redis
  depends_on:
   - init
   - mariadb
   - redis

 backup:
  container_name: backup
  image: mpgagebioinformatics/myapp:stable
  build:
    context: ./
    dockerfile: Dockerfile
    args:
      MYAPP_VERSION: dev
  user: root
  entrypoint: /myapp/services/backup/entrypoint.sh
  depends_on:
   - mariadb
   - init
  volumes:
   - ~/flaski3_backup/mariadb:/backup/mariadb
   - ~/flaski3_backup/users_data:/backup/users_data
   - data:/myapp_data/users:ro
  environment:
   - APP_NAME=myapp
   - APP_TITLE=flaski
   - DB_NAME=myapp
   - MYSQL_USER=myapp
   - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   - MYSQL_HOST=mariadb
   - MYSQL_PORT=3306
   - MAX_BACKUPS=15
   - INIT_BACKUP=0
   # Every day at 03:00
   - CRON_TIME=44 13 * * *
   - FLASK_ENV=backup
  restart: unless-stopped
  links:
   - mariadb

 mariadb:
  container_name: mariadb
  image: mariadb:10.5
  restart: always
  volumes:
   - db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

 redis:
  container_name: redis
  image: redis:6
  restart: always
  command: redis-server --requirepass ${REDIS_PASSWORD}

 nginx:
  container_name: nginx
  image: nginx:alpine
  restart: always
  ports:
   - 80:80
   - 443:443
  volumes:
   - ~/myapp/services/nginx/dev.conf:/etc/nginx/conf.d/default.conf:rw
   - ~/myapp_data/certificates/cert.pem:/certs/cert.pem:ro 
   - ~/myapp_data/certificates/key.pem:/certs/key.pem:ro
   - ~/myapp_data/certificates/dhparam.pem:/certs/dhparam.pem:ro
  links:
   - server
  depends_on:
   - server

volumes:
 data:
  external: false
 db:
  external: false